name: release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions: {}

env:
  ARCHIVE_JAVA_VERSION: 25

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download signal-cli build from CI workflow
        uses: actions/download-artifact@v8

      - name: Get signal-cli version
        id: version
        run: |
          mv ./signal-cli-archive-${{ env.ARCHIVE_JAVA_VERSION }}/* .
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: v${{ steps.version.outputs.version }}
          draft: false
          prerelease: true

      - name: Upload archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: signal-cli-${{ steps.version.outputs.version }}.tar.gz
          asset_name: signal-cli-${{ steps.version.outputs.version }}.tar.gz
          asset_content_type: application/x-compressed-tar

      - name: Upload Linux native archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: signal-cli-${{ steps.version.outputs.version }}-Linux-native.tar.gz
          asset_name: signal-cli-${{ steps.version.outputs.version }}-Linux-native.tar.gz
          asset_content_type: application/x-compressed-tar

      - name: Upload Linux client archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: signal-cli-${{ steps.version.outputs.version }}-Linux-client.tar.gz
          asset_name: signal-cli-${{ steps.version.outputs.version }}-Linux-client.tar.gz
          asset_content_type: application/x-compressed-tar
